import 'dart:async';

import 'package:alumni/core/network/status.dart';
import 'package:alumni/features/alumni_dashboard/screen/alumni_home_screen_after_login.dart';
import 'package:alumni/features/home/data/models/OTP_model/verify_OTP_Request_model.dart';
import 'package:alumni/features/home/data/models/login/login_request_model.dart';
import 'package:alumni/features/home/presentation/screen/dashboard_screen.dart';
import 'package:alumni/features/home/presentation/view_model/verify_and_login_view_model.dart';
import 'package:alumni/features/home/presentation/widgets/otp_text_field.dart';
import 'package:alumni/features/university_admin_dashboard/presentation/presentation/screen/after_login_home.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil_plus/flutter_screenutil_plus.dart';
import 'package:provider/provider.dart';

class OtpScreen extends StatefulWidget {
  final String mobileNo;

  const OtpScreen({
    required this.mobileNo,
    super.key,
  });

  @override
  State<OtpScreen> createState() => _OtpScreenState();
}

class _OtpScreenState extends State<OtpScreen> {
  // OTP received/generated by your application (debug only).
  String otp = "";

  late final List<TextEditingController> controller;
  late final List<FocusNode> focusNode;

  Timer? _timer;
  int count = 60;
  bool _isDisable = true;

  late final VerifyAndLoginViewModel _vm;

  @override
  void initState() {
    super.initState();

    controller = List.generate(6, (_) => TextEditingController());
    focusNode = List.generate(6, (_) => FocusNode());

    _vm = context.read<VerifyAndLoginViewModel>();

    // Clear verify/login state left over from a previous attempt.
    _vm.resetState(notify: false);

    _initializeOtp();
  }

  Future<void> _initializeOtp() async {
    try {
      final s = await _vm.getOtp();
      if (!mounted) return;
      setState(() => otp = s);
    } catch (e) {
      debugPrint("getOtp failed: $e");
    }

    if (!mounted) return;
    _startTimer();
  }

  void _startTimer() {
    _timer?.cancel();

    if (!mounted) return;

    setState(() {
      count = 60;
      _isDisable = true;
    });

    _timer = Timer.periodic(const Duration(seconds: 1), (timer) {
      if (!mounted) {
        timer.cancel();
        return;
      }

      setState(() {
        if (count > 0) count--;
        if (count == 0) {
          _isDisable = false;
          timer.cancel();
        }
      });
    });
  }

  void _showMessage(String message) {
    if (!mounted) return;
    ScaffoldMessenger.of(context)
      ..hideCurrentSnackBar()
      ..showSnackBar(SnackBar(content: Text(message)));
  }

  // ------------------------------------------------------------
  // OTP
  // ------------------------------------------------------------

  String _getEnteredOtp() {
    return controller.map((c) => c.text.trim()).join();
  }

  bool _isOtpComplete() {
    return controller.every((c) => c.text.trim().isNotEmpty);
  }

  int? _parseMobile() {
    return int.tryParse(widget.mobileNo.replaceAll(RegExp(r'\D'), ''));
  }

  void _clearOtpFields() {
    for (final c in controller) {
      c.clear();
    }
    focusNode.first.requestFocus();
  }

  Future<void> _verifyEnteredOtp() async {
    debugPrint("[OTP] _verifyEnteredOtp called");

    // Prevent double calls.
    final status = _vm.verifyOtpApiResponse.status;
    debugPrint("[OTP] current verify status = $status");
    if (status == Status.LOADING || status == Status.COMPLETE) {
      debugPrint("[OTP] stopped: already loading/complete");
      return;
    }

    final finalOTP = _getEnteredOtp();
    final mobile = _parseMobile();
    final otpInt = int.tryParse(finalOTP);

    debugPrint(
        "[OTP] raw mobileNo='${widget.mobileNo}' mobile=$mobile otp=$otpInt");

    if (finalOTP.length != 6 || otpInt == null) {
      debugPrint("[OTP] stopped: invalid otp");
      _showMessage("Please enter a valid 6-digit OTP");
      return;
    }

    if (mobile == null) {
      debugPrint("[OTP] stopped: invalid mobile number");
      _showMessage("Invalid mobile number: '${widget.mobileNo}'");
      return;
    }

    debugPrint("[OTP] calling verifyOTP...");

    await _vm.verifyOTP(
      VerifyOtpRequestModel(mobile: mobile, otp: otpInt),
    );

    debugPrint("[OTP] verify finished: ${_vm.verifyOtpApiResponse.status} "
        "${_vm.verifyOtpApiResponse.message}");

    if (!mounted) return;

    // On failure clear the boxes so the user can re-enter.
    if (_vm.verifyOtpApiResponse.status == Status.ERROR) {
      _clearOtpFields();
    }
  }

  void _onOtpChanged(String value, int index) {
    debugPrint(
        "[OTP] changed index=$index value='$value' complete=${_isOtpComplete()}");

    if (value.isNotEmpty && index < 5) {
      focusNode[index + 1].requestFocus();
    }

    // Check on every change, not only on the last box.
    if (_isOtpComplete()) {
      FocusScope.of(context).unfocus();
      _verifyEnteredOtp();
    }
  }

  void _onBackspace(int index) {
    if (index > 0) {
      controller[index - 1].clear();
      focusNode[index - 1].requestFocus();
    }
  }

  // ------------------------------------------------------------
  // LOGIN
  // ------------------------------------------------------------

  Future<void> _login() async {
    final finalOTP = _getEnteredOtp();
    if (finalOTP.length != 6) return;

    final mobile = _parseMobile();
    final otpInt = int.tryParse(finalOTP);
    if (mobile == null || otpInt == null) {
      _showMessage("Invalid mobile number or OTP");
      return;
    }

    await _vm.login(LoginRequestModel(mobile: mobile, otp: otpInt));

    if (!mounted) return;

    final response = _vm.loginApiResponse;

    if (response.status != Status.COMPLETE || response.data?.user == null) {
      return;
    }

    final roleId = response.data!.user!.roleId;

    final Widget destination;
    if (roleId == 2) {
      destination = AfterLoginHome();
    } else if (roleId == 7) {
      destination = AlumniHomeScreenAfterLogin();
    } else {
      destination = DashboardScreen();
    }

    Navigator.pushReplacement(
      context,
      MaterialPageRoute(builder: (_) => destination),
    );
  }

  // ------------------------------------------------------------
  // DISPOSE
  // ------------------------------------------------------------

  @override
  void dispose() {
    _timer?.cancel();

    for (final c in controller) {
      c.dispose();
    }
    for (final n in focusNode) {
      n.dispose();
    }

    super.dispose();
  }

  // ------------------------------------------------------------
  // UI
  // ------------------------------------------------------------

  Widget _buildButton({
    required String label,
    required Color color,
    required Color textColor,
    VoidCallback? onTap,
  }) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(12),
      child: Container(
        width: double.infinity,
        height: MediaQuery.of(context).size.height / 18,
        decoration: BoxDecoration(
          color: color,
          borderRadius: BorderRadius.circular(12),
        ),
        child: Center(
          child: Text(
            label,
            style: TextStyle(
              color: textColor,
              fontWeight: FontWeight.bold,
              fontSize: 15.sp,
            ),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final scheme = Theme.of(context).colorScheme;

    return Scaffold(
      backgroundColor: scheme.surface,
      appBar: AppBar(),
      body: SafeArea(
        child: SizedBox(
          height: MediaQuery.of(context).size.height,
          width: MediaQuery.of(context).size.width,
          child: Padding(
            padding: EdgeInsets.all(15.r),
            child: Column(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Column(
                  children: [
                    Padding(
                      padding: EdgeInsets.only(bottom: 8.r),
                      child: const Row(
                        children: [
                          Icon(Icons.lock, size: 30),
                          SizedBox(width: 8),
                          Text(
                            "Enter OTP Code",
                            style: TextStyle(
                              fontWeight: FontWeight.bold,
                              fontSize: 25,
                            ),
                          ),
                        ],
                      ),
                    ),

                    const Text(
                      "Please enter the 6-digit OTP sent to your registered mobile number to verify your identity",
                    ),

                    Padding(
                      padding: EdgeInsets.only(top: 60.r),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: [
                          // Debug only: never show the OTP in release builds.
                          if (kDebugMode) Text("OTP: $otp"),

                          // ------------------------------------------------
                          // OTP FIELDS
                          // ------------------------------------------------
                          SizedBox(
                            width: MediaQuery.of(context).size.width,
                            height: MediaQuery.of(context).size.height / 12,
                            child: Consumer<VerifyAndLoginViewModel>(
                              builder: (context, value, child) {
                                final status =
                                    value.verifyOtpApiResponse.status;
                                final fieldsEnabled =
                                    status != Status.COMPLETE &&
                                        status != Status.LOADING;

                                return Row(
                                  children: List.generate(6, (index) {
                                    return Expanded(
                                      child: Padding(
                                        padding: EdgeInsets.symmetric(
                                          horizontal: 4.w,
                                        ),
                                        child: OtpTextField(
                                          enabled: fieldsEnabled,
                                          controller: controller[index],
                                          node: focusNode[index],
                                          onChanged: (v) =>
                                              _onOtpChanged(v, index),
                                          onBackspace: () =>
                                              _onBackspace(index),
                                        ),
                                      ),
                                    );
                                  }),
                                );
                              },
                            ),
                          ),

                          Padding(
                            padding: EdgeInsets.all(15.r),
                            child: GestureDetector(
                              onTap: () => Navigator.pop(context),
                              child: Row(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  Padding(
                                    padding: EdgeInsets.only(right: 8.r),
                                    child: Icon(
                                      Icons.edit,
                                      color: scheme.secondary,
                                    ),
                                  ),
                                  Text(
                                    "Edit Mobile Number",
                                    style: TextStyle(
                                      color: scheme.secondary,
                                      fontSize: 15.sp,
                                      fontWeight: FontWeight.bold,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),

                          Text.rich(
                            TextSpan(
                              text: "You can resend the code in",
                              children: [
                                TextSpan(
                                  text: " $count",
                                  style: TextStyle(
                                    color: scheme.secondary,
                                    fontWeight: FontWeight.bold,
                                    fontSize: 16.sp,
                                  ),
                                ),
                                const TextSpan(text: " Second"),
                              ],
                            ),
                          ),

                          Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Text(
                                "Didn't receive the code? ",
                                style: TextStyle(
                                  color: Colors.grey.shade500,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                              GestureDetector(
                                onTap: _isDisable
                                    ? null
                                    : () {
                                  _vm.resetState();
                                  _clearOtpFields();
                                  _startTimer();
                                },
                                child: Text(
                                  "Resend OTP",
                                  style: TextStyle(
                                    color: _isDisable
                                        ? Colors.grey.shade500
                                        : scheme.secondary,
                                    fontWeight: FontWeight.bold,
                                    fontSize: 16.sp,
                                  ),
                                ),
                              ),
                            ],
                          ),

                          // ------------------------------------------------
                          // VERIFY STATUS
                          // ------------------------------------------------
                          Padding(
                            padding: EdgeInsets.only(top: 12.r),
                            child: Consumer<VerifyAndLoginViewModel>(
                              builder: (context, value, child) {
                                final res = value.verifyOtpApiResponse;

                                switch (res.status) {
                                  case Status.LOADING:
                                    return SizedBox(
                                      height: 30.w,
                                      width: 30.w,
                                      child: CircularProgressIndicator(
                                        color: scheme.secondary,
                                      ),
                                    );
                                  case Status.ERROR:
                                    return Text(
                                      res.message.toString(),
                                      style: const TextStyle(
                                        color: Colors.red,
                                      ),
                                    );
                                  case Status.COMPLETE:
                                    return const Text(
                                      "Verified",
                                      style: TextStyle(
                                        color: Colors.green,
                                        fontWeight: FontWeight.bold,
                                      ),
                                    );
                                  default:
                                    return const SizedBox.shrink();
                                }
                              },
                            ),
                          ),

                          Consumer<VerifyAndLoginViewModel>(
                            builder: (context, value, child) {
                              if (value.loginApiResponse.status ==
                                  Status.ERROR) {
                                return Padding(
                                  padding: EdgeInsets.only(top: 8.r),
                                  child: Text(
                                    value.loginApiResponse.message.toString(),
                                    textAlign: TextAlign.center,
                                    style: const TextStyle(color: Colors.red),
                                  ),
                                );
                              }
                              return const SizedBox.shrink();
                            },
                          ),
                        ],
                      ),
                    ),
                  ],
                ),

                // ----------------------------------------------------------
                // LOGIN BUTTON
                // ----------------------------------------------------------
                Consumer<VerifyAndLoginViewModel>(
                  builder: (context, value, child) {
                    // OTP is not verified yet.
                    if (value.verifyOtpApiResponse.status != Status.COMPLETE) {
                      return _buildButton(
                        label: "Verify OTP first",
                        color: Colors.grey.shade400,
                        textColor: Colors.white,
                      );
                    }

                    // Login API loading.
                    if (value.loginApiResponse.status == Status.LOADING) {
                      return Container(
                        width: double.infinity,
                        height: MediaQuery.of(context).size.height / 18,
                        decoration: BoxDecoration(
                          color: scheme.secondary,
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: Center(
                          child: CircularProgressIndicator(
                            color: scheme.surface,
                          ),
                        ),
                      );
                    }

                    // Login failed.
                    if (value.loginApiResponse.status == Status.ERROR) {
                      return _buildButton(
                        label: "Retry Login",
                        color: scheme.secondary,
                        textColor: Colors.white,
                        onTap: _login,
                      );
                    }

                    // Login button.
                    return _buildButton(
                      label: "Log In",
                      color: scheme.secondary,
                      textColor: scheme.surface,
                      onTap: _login,
                    );
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}